config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                                                                              Controller#Action
#                             root GET      /                                                                                        homes#top
#                 new_user_session GET      /users/sign_in(.:format)                                                                 devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                                                                 devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)                                                                devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)                                                           users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)                                                  users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)                                                            devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)                                                           devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)                                                                devise/passwords#update
#                                  PUT      /users/password(.:format)                                                                devise/passwords#update
#                                  POST     /users/password(.:format)                                                                devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                                                                  devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                                                                 devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                                                                    devise/registrations#edit
#                user_registration PATCH    /users(.:format)                                                                         devise/registrations#update
#                                  PUT      /users(.:format)                                                                         devise/registrations#update
#                                  DELETE   /users(.:format)                                                                         devise/registrations#destroy
#                                  POST     /users(.:format)                                                                         devise/registrations#create
#                content_favorites DELETE   /contents/:content_id/favorites(.:format)                                                favorites#destroy
#                                  POST     /contents/:content_id/favorites(.:format)                                                favorites#create
#                 content_comments DELETE   /contents/:content_id/comments(.:format)                                                 comments#destroy
#                                  POST     /contents/:content_id/comments(.:format)                                                 comments#create
#                 timeline_content GET      /contents/:id/timeline(.:format)                                                         contents#timeline
#                  search_contents GET      /contents/search(.:format)                                                               contents#search
#                  confirm_content GET      /contents/:id/confirm(.:format)                                                          contents#confirm
#                tag_field_content GET      /contents/:id/tag_field(.:format)                                                        contents#tag_field
#               mile_stone_content GET      /contents/:id/mile_stone(.:format)                                                       contents#mile_stone
#            edit_request_contents GET      /contents/edit_request(.:format)                                                         contents#edit_request
#                         contents GET      /contents(.:format)                                                                      contents#index
#                                  POST     /contents(.:format)                                                                      contents#create
#                      new_content GET      /contents/new(.:format)                                                                  contents#new
#                     edit_content GET      /contents/:id/edit(.:format)                                                             contents#edit
#                          content GET      /contents/:id(.:format)                                                                  contents#show
#                                  PATCH    /contents/:id(.:format)                                                                  contents#update
#                                  PUT      /contents/:id(.:format)                                                                  contents#update
#                                  DELETE   /contents/:id(.:format)                                                                  contents#destroy
#                     search_users GET      /users/search(.:format)                                                                  users#search
#                            users GET      /users(.:format)                                                                         users#index
#                                  POST     /users(.:format)                                                                         users#create
#                         new_user GET      /users/new(.:format)                                                                     users#new
#                        edit_user GET      /users/:id/edit(.:format)                                                                users#edit
#                             user GET      /users/:id(.:format)                                                                     users#show
#                                  PATCH    /users/:id(.:format)                                                                     users#update
#                                  PUT      /users/:id(.:format)                                                                     users#update
#                                  DELETE   /users/:id(.:format)                                                                     users#destroy
#                                  PUT      /users/follow/:user_id(.:format)                                                         users#follow
#                                  PUT      /users/unfollow/:user_id(.:format)                                                       users#unfollow
#                                  GET      /users/follow_list/:user_id(.:format)                                                    users#follow_list
#                                  GET      /users/follower_list/:user_id(.:format)                                                  users#follower_list
#                    notifications GET      /notifications(.:format)                                                                 notifications#index
#                       refile_app          /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#               rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :contents do                 
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    get :timeline, on: :member
    get :search, on: :collection 
    get :confirm, on: :member 
    get :tag_field, on: :member 
    get :mile_stone, on: :member
    get :edit_request, on: :collection
    #  collection = idがつかない
    #  member = idがつく
  end 

  resources :users do
    get :search, on: :collection
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
#フォローとフォローを外すアクション

get 'users/follow_list/:user_id' => 'users#follow_list'
get 'users/follower_list/:user_id' => 'users#follower_list'
#フォロー・フォロワーの一覧ページ

resources :notifications, only: :index
end
# bundle exec annotate --routes

app/models/content.rb
class Content < ApplicationRecord

    enum status: { draft: 0, published: 1 }
    # 下書きを0に設定し、公開の記事を１にする
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :favorites, dependent: :destroy
    validates :title, presence: true
    validates :tag_list, presence: true
    validates :body, presence: true
    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
    # user.idがfavoriteに存在するかどうか
    attachment :image

    # tagのgemようのモデル
    acts_as_taggable
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
    before_action :authenticate_user!
    def new
        @content = Content.new
    end
    def create
        @content = Content.new(content_params)
        @content.user_id = current_user.id
        if @content.save
        redirect_to content_path(@content)
        else 
        render 'new'
        end
    end
    def index
        # カミナリの実装をするので以下の変数に変える
        @contents = Content.published.order("created_at DESC").page(params[:page]).per(10)

        if params[:title].present?
            @content = Content.where('name LIKE ?', "%#{params[:title]}%")
        else
            @content = Content.none
        end
    end
    def show
        @comment = Comment.new
        @content = Content.find(params[:id])

        if  @content.nil?
        redirect_to root_path
        elsif @content.draft?
        login_required
        end
        # 条件分岐で下書きはログインしてないと見れなくする
    end

    def destroy
        @content = Content.find(params[:id])
        @content.destroy
        redirect_to contents_path
    end

    def search
        @content = Content.where('title LIKE ?', "%#{params[:title]}%")
    end

    def edit
        @content = Content.find(params[:id])
    end

    def update
        @content = Content.find(params[:id])
        @content.update(content_params)
        redirect_to content_path(@content.id)
    end

    def confirm
        @user = User.find(params[:id])
        @contents = @user.contents.draft.order("created_at DESC").page(params[:page]).per(10)
        # ユーザーの投稿した下書きを閲覧することができるようになる
    end

    def timeline
        #フォローしているユーザーのみタイムラインに表示
        #N+1問題を防ぐためにincludesメソッド(gem: bulletを導入)を使用
            @contents_all = Content.includes(:user)

            @user = User.find(current_user.id)
        #フォローしているユーザーを取得
            @follow_users = @user.all_following
        #フォローユーザーのツイートを表示
            @contents = @contents_all.where(user_id: @follow_users).order("created_at DESC").page(params[:page]).per(10)
    end

    def tag_field
        @contents = Content.published.order("created_at DESC").page(params[:page]).per(10)

        if params[:tag_name]
            @contents = Content.tagged_with("#{params[:tag_name]}")
        end
    end

    def mile_stone
        @contents = Content.find(Favorite.group(:content_id).order('count(content_id) desc').limit(10).pluck(:content_id))
    end

    def edit_request
        @user = User.find(current_user.id)
        @contents = @user.contents.page(params[:page]).reverse_order
    end


    private
    def content_params
        params.require(:content).permit(:title, :tag_list, :body, :status, :image)
    end

    def login_required
        redirect_to login_url unless current_user
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_left.html.slim
.col-md-2
  ul.list-group
    li.list-group-item
      strong
        = link_to 'トレンド', contents_path, class: 'glyphicon glyphicon-check'
    li.list-group-item
      strong
        = link_to 'タイムライン', timeline_content_path(current_user), class: 'glyphicon glyphicon-list'
    li.list-group-item
      strong
        = link_to 'タグフィールド', tag_field_content_path(current_user), class: 'glyphicon glyphicon-tags'
    li.list-group-item
      strong
        = link_to 'マイルストーン', mile_stone_content_path(current_user), class: 'glyphicon glyphicon-unchecked'

app/views/contents/_right.html.erb
<div class="col-md-3">
<h1>記事を検索</h1>
<p style='border-bottom: 3px solid red; text-align: center;'>タイトルを入力してください</p>
<%= form_with url: search_contents_path, method: :get, local: true do |f| %>
  <%= f.text_field :title %>
  <%= f.submit '検索', class: 'btn btn-success' %>
<% end %>
</div>

app/views/contents/confirm.html.erb
<div class="col-md-2">
</div>
<div class="col-md-7">
<h1>下書き記事の一覧</h1>
<table class='table table-hover table-inverse'>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td>
        <%= link_to(content) do %> 
         <%= attachment_image_tag(content.user, :profile_image, fallback: 'qiita.jpeg', size:'50x50') %>
        <%= content.title %> (<%= time_ago_in_words(content.created_at) %>前)
        <br>
        <%= link_to "#{content.comments.count} コメント", content_path(content.id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @contents, class: "paginate" %>
</div>
<div class="col-md-3">
<h1>記事を検索</h1>
<p style='border-bottom: 3px solid red; text-align: center;'>タイトルを入力してください</p>
<%= form_with url: search_contents_path, method: :get, local: true do |f| %>
  <%= f.text_field :title %>
  <%= f.submit '検索', class: 'btn btn-success' %>
<% end %>
</div>

app/views/contents/confirm.html.slim
.col-md-2

.col-md-7
  h1
    | 下書き記事の一覧
  table.table.table-hover.table-inverse
    tbody
      - @contents.each do |content|
        tr
          td
            = link_to(content) do
              = attachment_image_tag(content.user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
              = content.title
              |  (
              = time_ago_in_words(content.created_at)
              | 前) 
              br
              = link_to "#{content.comments.count} コメント", content_path(content.id)
  = paginate @contents, class: "paginate"
.col-md-3
  h1
    | 記事を検索
  p[style="border-bottom: 3px solid red; text-align: center;"]
    | タイトルを入力してください
  = form_with url: search_contents_path, method: :get, local: true do |f|
    = f.text_field :title
    = f.submit '検索', class: 'btn btn-success'

app/views/contents/edit.html.erb
<div class="col-md-12">
    <%= form_for @content do |f| %>
    <% if @content.errors.any? %>
        <%= @content.errors.count %>件のエラーが発生しました
        <% @content.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
            <%= f.select :status, Content.statuses.keys.map { |k| [t("enums.content.status.#{k}"),k]} %>
        <%= f.text_field :title, class: 'col-md-12 title',placeholder: 'タイトル', aria_label: 'タイトル' %>
        <%= f.text_field :tag_list, class: 'col-md-12 title' , placeholder: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0', aria_label: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0' %>
    </div>
        <%= f.attachment_field :image, class: 'col-md-12 title', placeholder: '写真を送付', aria_label: '写真を送付' %>
        <%= f.text_area :body, class: 'col-md-12 body', placeholder:'プログラミング知識をMarkdown記法で書いて共有しよう', aria_label: 'プログラミング知識をMarkdown記法で書いて共有しよう' %>
    </div>         
    <div class="actions row">
        <%= f.submit '編集',class: 'btn btn-success col-md-offset-11 col-md-1 action'%>
    </div>
<% end %>

app/views/contents/edit.html.slim
.col-md-12
  = form_for @content do |f|
    - if @content.errors.any?
      = @content.errors.count
      | 件のエラーが発生しました 
      - @content.errors.full_messages.each do |message|
        = message
    = f.select :status, Content.statuses.keys.map { |k| [t("enums.content.status.#{k}"),k]}
    = f.text_field :title, class: 'col-md-12 title',placeholder: 'タイトル', aria_label: 'タイトル'
    = f.text_field :tag, class: 'col-md-12 title' , placeholder: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0', aria_label: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0'
= f.attachment_field :image, class: 'col-md-12 title', placeholder: '写真を送付', aria_label: '写真を送付'
= f.text_area :body, class: 'col-md-12 body', placeholder:'プログラミング知識をMarkdown記法で書いて共有しよう', aria_label: 'プログラミング知識をMarkdown記法で書いて共有しよう'
.actions.row
  = f.submit '編集',class: 'btn btn-success col-md-offset-11 col-md-1 action'

app/views/contents/edit_request.html.slim
.col-md-3
h1[style='text-align: center;'] あなたが編集することができる投稿一覧
table.table.table-hover.table-inverse
    tbody
      - @contents.each do |content|
        tr
          td
            = link_to(content) do
              = content.title
              |  (
              = time_ago_in_words(content.created_at)
              | 前) 
            br
            = link_to(content) do
              = link_to "#{content.comments.count} コメント", content_path(content.id)
= render 'right'

app/views/contents/index.html.slim
= render 'left'
.col-md-7
  h5
    span.glyphicon.glyphicon-check[aria-hidden="true"]
    |  トレンド
  div[style="color: #aaa;"]
    | 記事の新規順に表示
  table.table.table-hover.table-inverse
    tbody
      - @contents.each do |content|
        tr
          td
            = link_to(content.user) do
              = attachment_image_tag(content.user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
            = link_to(content) do
              = content.title
              |  (
              = time_ago_in_words(content.created_at)
              | 前) 
            = link_to(content.user) do
              span[style="color: #aaa;"]
                | by 
                = content.user.name
            br
            = link_to(content) do
              = link_to "#{content.comments.count} コメント", content_path(content.id)
  = paginate @contents, class: "paginate"
= render 'right'

app/views/contents/mile_stone.html.slim
= render 'left'
.col-md-7
  h5
    span.glyphicon.glyphicon-unchecked[aria-hidden="true"]
    |  マイルストーン
  div[style="color: #aaa;"]
    | 最もいいねの多い記事を10 個表示
  table.table.table-hover.table-inverse
    tbody
      - @contents.each do |content|
        tr
          td
            span[style="font-size: 20px; color: red;"]
              = content.favorites.count
            |  いいね 
            br
            = link_to(content.user) do
              = attachment_image_tag(content.user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
              |  <ruby code=" end %>
              = link_to(content) do "> 
              -         <%= content.title
              |  (
              = time_ago_in_words(content.created_at)
              | 前) 
            = link_to(content.user) do
              span[style="color: #aaa;"]
                | by 
                = content.user.name
              |  <ruby code=" end %> 
              br
              = link_to(content) do ">
              -         <%= link_to "#{content.comments.count} コメント", content_path(content.id)
= render 'right'

app/views/contents/new.html.erb
<div class="col-md-12">
    <%= form_for @content do |f| %>
    <% if @content.errors.any? %>
        <%= @content.errors.count %>件のエラーが発生しました
        <% @content.errors.full_messages.each do |message| %>
            <%= message %>
        <% end %>
    <% end %>
        <%= f.select :status, Content.statuses.keys.map { |k| [t("enums.content.status.#{k}"),k]} %>
        <!--form.select :statusでstatusカラムをセレクトボックスで選択できるようにする-->
        <%= f.text_field :title, class: 'col-md-12 title',placeholder: 'タイトル', aria_label: 'タイトル' %>
        <%= f.text_field :tag_list, value: @content.tag_list.join(','), class: 'col-md-12 title' , placeholder: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0', aria_label: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0' %>
        <%# valueを設定しているので複数のタグを作成することができるようになっている %>
    </div>
        <%= f.attachment_field :image, class: 'col-md-12 title', placeholder: '写真を送付', aria_label: '写真を送付' %>
        <%= f.text_area :body, class: 'col-md-12 body', placeholder:'プログラミング知識をMarkdown記法で書いて共有しよう', aria_label: 'プログラミング知識をMarkdown記法で書いて共有しよう' %>
    </div>         
    <div class="actions row">
        <%= f.submit 'Qiitaに投稿',class: 'btn btn-success col-md-offset-11 col-md-1 action'%>
    </div>
<% end %>

app/views/contents/new.html.slim
.col-md-12
  = form_for @content do |f|
    - if @content.errors.any?
      = @content.errors.count
      | 件のエラーが発生しました 
      - @content.errors.full_messages.each do |message|
        = message
    = f.select :status, Content.statuses.keys.map { |k| [t("enums.content.status.#{k}"),k]}
    = f.text_field :title, class: 'col-md-12 title',placeholder: 'タイトル', aria_label: 'タイトル'
    = f.text_field :tag, class: 'col-md-12 title' , placeholder: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0', aria_label: 'プログラミング技術に関連するタグをスペース区切りで5つまで入力（例: Ruby Rails:4.2.0'
= f.attachment_field :image, class: 'col-md-12 title', placeholder: '写真を送付', aria_label: '写真を送付'
= f.text_area :body, class: 'col-md-12 body', placeholder:'プログラミング知識をMarkdown記法で書いて共有しよう', aria_label: 'プログラミング知識をMarkdown記法で書いて共有しよう'
.actions.row
  = f.submit 'Qiitaに投稿',class: 'btn btn-success col-md-offset-11 col-md-1 action'

app/views/contents/show.html.erb
<div class ="col-md-1">
<% if @content.favorited_by?(current_user) %> 
    <%= link_to content_favorites_path(@content), method: :delete do %>
      <i class="glyphicon glyphicon-heart" style='color: pink; font-size: 40px;'></i> <br>
      <span style="font-size: 20px;"><%= @content.favorites.count  %></span> いいね
    <% end %>
<% else %>
    <%= link_to content_favorites_path(@content), method: :post do %>
      <i class="glyphicon glyphicon-heart" style='color: pink; font-size: 40px;'></i> <br>
      <span style="font-size: 20px;"><%= @content.favorites.count  %></span> いいね
    <% end %>
<% end %>
</div>

<div class ="col-md-7">
<% if @content.user == current_user %>
<%= link_to '編集する(公開&非公開を含む)', edit_content_path(@content), class: 'glyphicon glyphicon-pencil' %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">メニュー1</a></li>
            <li><a href="#">メニュー2</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to '削除', @content, method: :delete, data: { confirm: '本当に消しますか？' } %></li>
          </ul>
        </li>
<% end %>
<h1 style='border-bottom: 10px solid yellow; text-align: center;'><strong class="big-title">
<span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>   
<%= @content.title %></strong></h1>
<h2 style='text-align: center;'><%= render 'tag_list', tag_list: @content.tag_list %></h2>
<br> <br> <br> 
<% if @content.image != nil %>
<%= attachment_image_tag(@content, :image, fallback: 'qiita.jpeg', size:'656x437') %><br> <br> <br>
<% end %>
<span style='font-size: 20px;'><%= markdown(@content.body).html_safe %></span>
</div>

<div class = 'col-md-4'>
<div class="comment-list bt style-2" id="comments">
    <div class="float-wrapper">
        <h2 class="comment-count"><%= @content.comments.count %>件コメント</h2>
    </div>

<ol>
    <% @content.comments.each do |comment| %>
        <li>
            
                    <%= link_to (comment.user) do %>
                        <%= comment.user.name %>
                    <% end %>
                        <%= comment.created_at.strftime('%Y/%m/%d') %> <br>
                    <%= comment.comment %>
                
        </li>
    <% end %>
</ol>

<%= form_for [@content, @comment] do |f| %>
    <div class="row">
        <div class="col-md-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "記事へのコメントはここに" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right btn-primary" %>
<% end %>
</div>
</div>

app/views/contents/show.html.slim
.col-md-1
  - if @content.favorited_by?(current_user)
    = link_to content_favorites_path(@content), method: :delete do
      i.glyphicon.glyphicon-heart[style="color: pink; font-size: 40px;"]
      br
      span[style="font-size: 20px;"]
        = @content.favorites.count
      |  いいね 
  - else
    = link_to content_favorites_path(@content), method: :post do
      i.glyphicon.glyphicon-heart[style="color: pink; font-size: 40px;"]
      br
      span[style="font-size: 20px;"]
        = @content.favorites.count
      |  いいね 
.col-md-7
  - if @content.user == current_user
    = link_to '編集する(公開&非公開を含む)', edit_content_path(@content), class: 'glyphicon glyphicon-pencil'
    li.dropdown
      a.dropdown-toggle[href="#" data-toggle="dropdown"]
        span.glyphicon.glyphicon-cog[aria-hidden="true"]
        span.caret
      ul.dropdown-menu
        li
          a[href="#"]
            | メニュー1
        li
          a[href="#"]
            | メニュー2
        li.divider[role="separator"]
        li
          = link_to '削除', @content, method: :delete, data: { confirm: '本当に消しますか？' }
  h1[style="border-bottom: 10px solid yellow; text-align: center;"]
    strong.big-title
      span.glyphicon.glyphicon-ok-sign[aria-hidden="true"]
      = @content.title
  h2[style="text-align: center;"]
    span.label.label-default
      = @content.tag
  br
  br
  br
  - if @content.image != nil
    = attachment_image_tag(@content, :image, fallback: 'qiita.jpeg', size:'656x437')
    br
    br
    br
  span[style="font-size: 20px;"]
    = markdown(@content.body).html_safe
.col-md-4
  #comments.comment-list.bt.style-2
    .float-wrapper
      h2.comment-count
        = @content.comments.count
        | 件コメント
    ol
      - @content.comments.each do |comment|
        li
          = link_to (comment.user) do
            = comment.user.name
          = comment.created_at.strftime('%Y/%m/%d')
          br
          = comment.comment
    = form_for [@content, @comment] do |f|
      .row
        .col-md-12
          = f.text_area :comment, rows:'5', class: "form-control",placeholder: "記事へのコメントはここに"
      = f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right btn-primary"

app/views/contents/timeline.html.erb
<%= render 'left' %>
<div class="col-md-7">
<h5><span class="glyphicon glyphicon-list" aria-hidden="true"></span> タイムライン<div style='color: #aaa;'>フォローしているユーザーの投稿のみを表示</div></h5>
<table class='table table-hover table-inverse'>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td>
        <%= link_to(content.user) do %>
         <%= attachment_image_tag(content.user, :profile_image, fallback: 'qiita.jpeg', size:'50x50') %>
         <% end %><%= link_to(content) do %> 
        <%= content.title %> (<%= time_ago_in_words(content.created_at) %>前)
        <% end %>
        <%= link_to(content.user) do %>
        <span style="color: #aaa;">by <%= content.user.name %></span>
        <% end %> <br> <%= link_to(content) do %>
        <%= link_to "#{content.comments.count} コメント", content_path(content.id) %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= render 'right' %>