config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                                                                              Controller#Action
#                             root GET      /                                                                                        homes#top
#                 new_user_session GET      /users/sign_in(.:format)                                                                 devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                                                                 devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)                                                                devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)                                                           users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)                                                  users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)                                                            devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)                                                           devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)                                                                devise/passwords#update
#                                  PUT      /users/password(.:format)                                                                devise/passwords#update
#                                  POST     /users/password(.:format)                                                                devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                                                                  devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                                                                 devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                                                                    devise/registrations#edit
#                user_registration PATCH    /users(.:format)                                                                         devise/registrations#update
#                                  PUT      /users(.:format)                                                                         devise/registrations#update
#                                  DELETE   /users(.:format)                                                                         devise/registrations#destroy
#                                  POST     /users(.:format)                                                                         devise/registrations#create
#                content_favorites DELETE   /contents/:content_id/favorites(.:format)                                                favorites#destroy
#                                  POST     /contents/:content_id/favorites(.:format)                                                favorites#create
#                 content_comments DELETE   /contents/:content_id/comments(.:format)                                                 comments#destroy
#                                  POST     /contents/:content_id/comments(.:format)                                                 comments#create
#                 timeline_content GET      /contents/:id/timeline(.:format)                                                         contents#timeline
#                  search_contents GET      /contents/search(.:format)                                                               contents#search
#                  confirm_content GET      /contents/:id/confirm(.:format)                                                          contents#confirm
#                tag_field_content GET      /contents/:id/tag_field(.:format)                                                        contents#tag_field
#               mile_stone_content GET      /contents/:id/mile_stone(.:format)                                                       contents#mile_stone
#            edit_request_contents GET      /contents/edit_request(.:format)                                                         contents#edit_request
#                         contents GET      /contents(.:format)                                                                      contents#index
#                                  POST     /contents(.:format)                                                                      contents#create
#                      new_content GET      /contents/new(.:format)                                                                  contents#new
#                     edit_content GET      /contents/:id/edit(.:format)                                                             contents#edit
#                          content GET      /contents/:id(.:format)                                                                  contents#show
#                                  PATCH    /contents/:id(.:format)                                                                  contents#update
#                                  PUT      /contents/:id(.:format)                                                                  contents#update
#                                  DELETE   /contents/:id(.:format)                                                                  contents#destroy
#                     search_users GET      /users/search(.:format)                                                                  users#search
#                            users GET      /users(.:format)                                                                         users#index
#                                  POST     /users(.:format)                                                                         users#create
#                         new_user GET      /users/new(.:format)                                                                     users#new
#                        edit_user GET      /users/:id/edit(.:format)                                                                users#edit
#                             user GET      /users/:id(.:format)                                                                     users#show
#                                  PATCH    /users/:id(.:format)                                                                     users#update
#                                  PUT      /users/:id(.:format)                                                                     users#update
#                                  DELETE   /users/:id(.:format)                                                                     users#destroy
#                                  PUT      /users/follow/:user_id(.:format)                                                         users#follow
#                                  PUT      /users/unfollow/:user_id(.:format)                                                       users#unfollow
#                                  GET      /users/follow_list/:user_id(.:format)                                                    users#follow_list
#                                  GET      /users/follower_list/:user_id(.:format)                                                  users#follower_list
#                    notifications GET      /notifications(.:format)                                                                 notifications#index
#                       refile_app          /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#               rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :contents do                 
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    get :timeline, on: :member
    get :search, on: :collection 
    get :confirm, on: :member 
    get :tag_field, on: :member 
    get :mile_stone, on: :member
    get :edit_request, on: :collection
    #  collection = idがつかない
    #  member = idがつく
  end 

  resources :users do
    get :search, on: :collection
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
#フォローとフォローを外すアクション

get 'users/follow_list/:user_id' => 'users#follow_list'
get 'users/follower_list/:user_id' => 'users#follower_list'
#フォロー・フォロワーの一覧ページ

resources :notifications, only: :index
end
# bundle exec annotate --routes

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
        # ユーザー名
         has_many :contents, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
        # ユーザーの写真を使用するもの
         attachment :profile_image

          validates :email, presence: true
          validates :password, length: { minimum: 6 }, on: :create

          acts_as_followable # フォロワー機能
          acts_as_follower   # フォロー機能

          # お知らせ機能
          has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
          has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
   
          def create_notification_follow!(current_user)
            temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
            if temp.blank?
              notification = current_user.active_notifications.new(
                visited_id: id,
                action: 'follow'
              )
              notification.save if notification.valid?
            end
          end

          # facebookのouath認証
          def self.find_for_oauth(auth)
            user = User.where(uid: auth.uid, provider: auth.provider).first
        
            unless user
              user = User.create(
                uid:      auth.uid,
                provider: auth.provider,
                email:    auth.info.email,
                password: Devise.friendly_token[0, 20]
              )
            end
            user
          end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
      callback_from :facebook
    end
  
    private
    def callback_from(provider)
      provider = provider.to_s
  
      @user = User.find_for_oauth(request.env['omniauth.auth'])
  
      if @user.persisted?
        flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
        sign_in_and_redirect @user, event: :authentication
      else
        session["devise.#{provider}_data"] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end
    
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :screen_user, only: [:edit, :update]
    def show
        @user = User.find(params[:id])
        # 投稿したユーザーの作品を表示
        @contents = @user.contents.published.page(params[:page]).reverse_order  
    end

    def edit
        @user = User.find(params[:id])
    end

    def index
        @users = User.page(params[:page]).reverse_order

        if params[:name].present?
            @user = User.where('name LIKE ?', "%#{params[:name]}%")
        else
            @user = User.none
        end
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
      	redirect_to user_path(@user)
    end

    def search
          @user = User.where('name LIKE ?', "%#{params[:name]}%")
    end

    def follow
        @user = User.find(params[:user_id])
        current_user.follow(@user)
        @user.create_notification_follow!(current_user)
        redirect_to user_path(@user)
    end
  #フォローする
  
    def unfollow
        @user = User.find(params[:user_id])
        current_user.stop_following(@user)
        redirect_to user_path(@user)
    end
  #フォローを外す
  
  
    def follow_list
      @user = User.find(params[:user_id])
    end
  #フォローしてる人の一覧ページ
  
    def follower_list
      @user = User.find(params[:user_id])
    end
  #フォロワーの一覧ページ

  # ユーザーのアカウントの削除
    def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to root_path
    end

    private 
    def user_params
        params.require(:user).permit(:name, :first_name, :last_name, :profile_image,
         :check_email, :site, :company, :from, :introduction)
    end

    def screen_user
    	unless params[:id].to_i == current_user.id #スクリーンのユーザーかどうかを確かめる
    		redirect_to user_path(current_user)
    	end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form">
  <% if current_user.following? @user %>
    <%= link_to "UnFollow", {controller: :users,action: :unfollow,user_id: @user.id}, method: :put, class: 'btn btn-warning btn-lg active glyphicon glyphicon-thumbs-down' %>
  <% else %>
    <%= link_to "Follow", {controller: :users,action: :follow,user_id: @user.id}, method: :put, class: 'btn btn-success btn-lg active glyphicon glyphicon-thumbs-up' %>
  <% end %>
  </div>
<!--フォローしてたらフォロー解除ボタンを、フォローしてなかったらフォローボタンを表示-->

app/views/users/_follow_form.html.slim
#follow_form
  - if current_user.following? @user
    = link_to "UnFollow", {controller: :users,action: :unfollow,user_id: @user.id}, method: :put, class: 'btn btn-warning btn-lg active glyphicon glyphicon-thumbs-down'
  - else
    = link_to "Follow", {controller: :users,action: :follow,user_id: @user.id}, method: :put, class: 'btn btn-success btn-lg active glyphicon glyphicon-thumbs-up'

app/views/users/edit.html.erb
<div class="col-md-offset-3 col-md-7 edit" >
<h2>
<%= attachment_image_tag(@user, :profile_image, fallback: 'qiita.jpeg', size:'27x27') %>
<%= @user.name %> アカウント  <br> <strong> 
公開用プロフィール
</strong></h2>
<h5><strong>名前</strong></h5>
<%= bootstrap_form_for @user do |f| %>
        <%= f.text_field :name, class: 'col-md-5 title2',placeholder: '表示名', aria_label: '表示名'  %>
        <%= f.text_field :first_name, class: 'col-md-5  title',placeholder: '名', aria_label: '名' %>
        <%= f.text_field :last_name, class: 'col-md-5 title',placeholder: '姓', aria_label: '姓' %> 
        <br> <br> <br>
        <h5>写真の変更</h5>
        <%= f.attachment_field :profile_image %>　
        <h5>公開メールアドレス</h5> 
        <%= f.check_box :check_email %>メールアドレスをメールアドレスを全体に公開する <br>
        （誰もがあなたのメールアドレスを閲覧できるようになります）
        <h5>サイト/ブログ</h5>
        <%= f.text_field :site, class: 'col-md-12 title' %>
        <h5>所属している組織・会社</h5>
        <%= f.text_field :company, class: 'col-md-12 title' %>
        <h5>移住地</h5>
        <%= f.text_field :from, class: 'col-md-12 title' %>
        <h5>自己紹介</h5>
        <%= f.text_area :introduction, class: 'col-md-12 sub-body' %>
    <div class="actions row">
        <%= f.submit 'Qiitaに投稿',class: 'btn btn-success'%>
    </div>
<% end %>
<h3><%= link_to '※アカウントを削除する', user_path(@user), method: :delete, data: { confirm: 'はいを押すとアカウントが削除されますがよろしいですか？' } %></h3>
</div>

app/views/users/edit.html.slim
.col-md-offset-3.col-md-7.edit
  h2
    = attachment_image_tag(@user, :profile_image, fallback: 'qiita.jpeg', size:'27x27')
    = @user.name
    |  アカウント 
    br
    strong
      |  公開用プロフィール 
  h5
    strong
      | 名前
  = bootstrap_form_for @user do |f|
    = f.text_field :first_name, class: 'col-md-5  title',placeholder: '名', aria_label: '名'
    = f.text_field :last_name, class: 'col-md-5 title',placeholder: '姓', aria_label: '姓'
    br
    br
    br
    h5
      | 写真の変更
    = f.attachment_field :profile_image
    | 　 
    h5
      | 公開メールアドレス
    = f.check_box :check_email
    | メールアドレスをメールアドレスを全体に公開する 
    br
    |  （誰もがあなたのメールアドレスを閲覧できるようになります） 
    h5
      | サイト/ブログ
    = f.text_field :site, class: 'col-md-12 title'
    h5
      | 所属している組織・会社
    = f.text_field :company, class: 'col-md-12 title'
    h5
      | 移住地
    = f.text_field :from, class: 'col-md-12 title'
    h5
      | 自己紹介
    = f.text_area :introduction, class: 'col-md-12 sub-body'
    .actions.row
      = f.submit 'Qiitaに投稿',class: 'btn btn-success'

app/views/users/follow_list.html.erb
<h1><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong> フォロー一覧</strong></h1>
<table class='table table-hover table-inverse'>
  <tbody>
    <% @user.all_following.each do |user| %>
      <tr>
        <td>
        <%= link_to(user) do %> 
        <%= attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50') %>
        <%= user.name %> <br>
        <% end %>
        <%= user.introduction %>
        </td>
      </tr>   
    <% end %>
  </tbody>
</table>

app/views/users/follow_list.html.slim
h1
  span.glyphicon.glyphicon-user[aria-hidden="true"]
  strong
    |  フォロー一覧
table.table.table-hover.table-inverse
  tbody
    - @user.all_following.each do |user|
      tr
        td
          = link_to(user) do
            = attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
            = user.name
            br
          = user.introduction

app/views/users/follower_list.html.erb
<h1><span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong> フォロワー一覧</strong></h1>
<table class='table table-hover table-inverse'>
  <tbody>
    <% @user.followers.each do |user| %>
      <tr>
        <td>
        <%= link_to(user) do %> 
        <%= attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50') %>
        <%= user.name %> <br>
        <% end %>
        <%= user.introduction %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follower_list.html.slim
h1
  span.glyphicon.glyphicon-user[aria-hidden="true"]
  strong
    |  フォロワー一覧
table.table.table-hover.table-inverse
  tbody
    - @user.followers.each do |user|
      tr
        td
          = link_to(user) do
            = attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
            = user.name
            br
          = user.introduction

app/views/users/index.html.erb
<div class="col-md-2">
<h2><strong>ユーザー一覧</strong></h2>
Qiitaに登録しているユーザーの一覧です。<br>
 現在1万人以上のユーザーが登録しています。
</div>
<div class="col-md-7">
<table class='table table-hover table-inverse'>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>
        <%= link_to(user) do %> 
        <%= attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50') %>
        <%= user.name %> <br>
        <% end %>
        <%= user.introduction %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @users, class: "paginate" %>
</div>

<div class="col-md-3">
<h1>ユーザーを検索</h1>
<p style='border-bottom: 3px solid red; text-align: center;'>名前を入力してください</p>
<%= form_with url: search_users_path, method: :get, local: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit '検索', class: 'btn btn-success' %>
<% end %>
</div>

app/views/users/index.html.slim
.col-md-2
  h2
    strong
      | ユーザー一覧
  |  Qiitaに登録しているユーザーの一覧です。
  br
  |  現在1万人以上のユーザーが登録しています。 
.col-md-7
  table.table.table-hover.table-inverse
    tbody
      - @users.each do |user|
        tr
          td
            = link_to(user) do
              = attachment_image_tag(user, :profile_image, fallback: 'qiita.jpeg', size:'50x50')
              = user.name
              br
            = user.introduction
  = paginate @users, class: "paginate"
.col-md-3
  h1
    | ユーザーを検索
  p[style="border-bottom: 3px solid red; text-align: center;"]
    | 名前を入力してください
  = form_with url: search_users_path, method: :get, local: true do |f|
    = f.text_field :name
    = f.submit '検索', class: 'btn btn-success'

app/views/users/search.html.erb
<h1>検索結果</h1> <br>
<table>
  <thead>
    <tr>
      <th><h3>名前</h3></th>
    </tr>
  </thead>

  <table class='table table-hover table-inverse'>
  <tbody>
    <% @user.each do |user| %>
              <tr>
                <td><span style="font-size: 30px;"><%= link_to user.name, user %></span>さんでよろしいですか？</td>
            </tr>
    <% end %>
  </tbody>
  </table>
</table>

app/views/users/search.html.slim
h1
  | 検索結果
br
table
  thead
    tr
      th
        h3
          | 名前
  table.table.table-hover.table-inverse
    tbody
      - @user.each do |user|
        tr
          td
            span[style="font-size: 30px;"]
              = link_to user.name, user
            | さんでよろしいですか？

app/views/users/show.html.erb
<div class="col-md-3">
<!--fallbackを記述するときのサイズ指定の仕方-->
<%= attachment_image_tag(@user, :profile_image, fallback: 'qiita.jpeg', size:'200x200') %><br>
<h3><strong><%= @user.last_name %> <%= @user.first_name %></strong></h3>
<% if @user.check_email == true  %>
<span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= @user.email %> <br>
<% end %>
<span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span> <%= @user.company %> <br>
<span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span> <%= @user.from %> <br>
<% if @user.id == current_user.id %>
<%= link_to 'プロフィールを編集する', edit_user_path, class: 'glyphicon glyphicon-cog' %>
<% end %>
</div>

<div class="col-md-6">
<table class='table table-hover table-inverse'>
<h1><strong><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> このユーザーの投稿一覧</strong></h1>
  <tbody>
    <% @contents.each do |content| %>
      <tr>
        <td>
        <%= link_to(content) do %> 
        <%= content.title %> (<%= content.created_at.strftime('%Y/%m/%d') %>)
                     <br> <%= link_to "#{content.comments.count} コメント", content_path(content.id) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @contents, class: "paginate" %>
</div>

<div class="col-md-3">
<h3><strong><span class="glyphicon glyphicon-hand-up" aria-hidden="true"></span>     <%= @user.follow_count %>
<%= link_to "フォロー", {controller: :users,action: :follow_list,user_id: @user.id}, method: :get %></strong></h3> <br>
<!--クリックすると、フォローリストに飛ぶ-->
<h3><strong><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>    <%= @user.followers_count %>
<%= link_to "フォロワー", {controller: :users,action: :follower_list,user_id: @user.id}, method: :get %></strong></h3>
<!--クリックすると、フォロワーリストに飛ぶ-->

<% if current_user.id != @user.id %>
  <%= render 'follow_form' %>
<% end %>
<!--ユーザーがカレントユーザーじゃなかったら、'_follow_form.html.erb'を表示-->
</div>