config/routes.rb
# == Route Map
#
#                           Prefix Verb     URI Pattern                                                                              Controller#Action
#                             root GET      /                                                                                        homes#top
#                 new_user_session GET      /users/sign_in(.:format)                                                                 devise/sessions#new
#                     user_session POST     /users/sign_in(.:format)                                                                 devise/sessions#create
#             destroy_user_session DELETE   /users/sign_out(.:format)                                                                devise/sessions#destroy
# user_facebook_omniauth_authorize GET|POST /users/auth/facebook(.:format)                                                           users/omniauth_callbacks#passthru
#  user_facebook_omniauth_callback GET|POST /users/auth/facebook/callback(.:format)                                                  users/omniauth_callbacks#facebook
#                new_user_password GET      /users/password/new(.:format)                                                            devise/passwords#new
#               edit_user_password GET      /users/password/edit(.:format)                                                           devise/passwords#edit
#                    user_password PATCH    /users/password(.:format)                                                                devise/passwords#update
#                                  PUT      /users/password(.:format)                                                                devise/passwords#update
#                                  POST     /users/password(.:format)                                                                devise/passwords#create
#         cancel_user_registration GET      /users/cancel(.:format)                                                                  devise/registrations#cancel
#            new_user_registration GET      /users/sign_up(.:format)                                                                 devise/registrations#new
#           edit_user_registration GET      /users/edit(.:format)                                                                    devise/registrations#edit
#                user_registration PATCH    /users(.:format)                                                                         devise/registrations#update
#                                  PUT      /users(.:format)                                                                         devise/registrations#update
#                                  DELETE   /users(.:format)                                                                         devise/registrations#destroy
#                                  POST     /users(.:format)                                                                         devise/registrations#create
#                content_favorites DELETE   /contents/:content_id/favorites(.:format)                                                favorites#destroy
#                                  POST     /contents/:content_id/favorites(.:format)                                                favorites#create
#                 content_comments DELETE   /contents/:content_id/comments(.:format)                                                 comments#destroy
#                                  POST     /contents/:content_id/comments(.:format)                                                 comments#create
#                 timeline_content GET      /contents/:id/timeline(.:format)                                                         contents#timeline
#                  search_contents GET      /contents/search(.:format)                                                               contents#search
#                  confirm_content GET      /contents/:id/confirm(.:format)                                                          contents#confirm
#                tag_field_content GET      /contents/:id/tag_field(.:format)                                                        contents#tag_field
#               mile_stone_content GET      /contents/:id/mile_stone(.:format)                                                       contents#mile_stone
#            edit_request_contents GET      /contents/edit_request(.:format)                                                         contents#edit_request
#                         contents GET      /contents(.:format)                                                                      contents#index
#                                  POST     /contents(.:format)                                                                      contents#create
#                      new_content GET      /contents/new(.:format)                                                                  contents#new
#                     edit_content GET      /contents/:id/edit(.:format)                                                             contents#edit
#                          content GET      /contents/:id(.:format)                                                                  contents#show
#                                  PATCH    /contents/:id(.:format)                                                                  contents#update
#                                  PUT      /contents/:id(.:format)                                                                  contents#update
#                                  DELETE   /contents/:id(.:format)                                                                  contents#destroy
#                     search_users GET      /users/search(.:format)                                                                  users#search
#                            users GET      /users(.:format)                                                                         users#index
#                                  POST     /users(.:format)                                                                         users#create
#                         new_user GET      /users/new(.:format)                                                                     users#new
#                        edit_user GET      /users/:id/edit(.:format)                                                                users#edit
#                             user GET      /users/:id(.:format)                                                                     users#show
#                                  PATCH    /users/:id(.:format)                                                                     users#update
#                                  PUT      /users/:id(.:format)                                                                     users#update
#                                  DELETE   /users/:id(.:format)                                                                     users#destroy
#                                  PUT      /users/follow/:user_id(.:format)                                                         users#follow
#                                  PUT      /users/unfollow/:user_id(.:format)                                                       users#unfollow
#                                  GET      /users/follow_list/:user_id(.:format)                                                    users#follow_list
#                                  GET      /users/follower_list/:user_id(.:format)                                                  users#follower_list
#                    notifications GET      /notifications(.:format)                                                                 notifications#index
#                       refile_app          /attachments                                                                             #<Refile::App app_file="/home/vagrant/.bundle/ruby/2.5.0/refile-46b4178654e6/lib/refile/app.rb">
#               rails_service_blob GET      /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET      /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET      /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT      /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST     /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

Rails.application.routes.draw do
  root 'homes#top'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :contents do                 
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
    get :timeline, on: :member
    get :search, on: :collection 
    get :confirm, on: :member 
    get :tag_field, on: :member 
    get :mile_stone, on: :member
    get :edit_request, on: :collection
    #  collection = idがつかない
    #  member = idがつく
  end 

  resources :users do
    get :search, on: :collection
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
#フォローとフォローを外すアクション

get 'users/follow_list/:user_id' => 'users#follow_list'
get 'users/follower_list/:user_id' => 'users#follower_list'
#フォロー・フォロワーの一覧ページ

resources :notifications, only: :index
end
# bundle exec annotate --routes

app/views/layouts/_footer.html.erb
<div class="row" style='margin-top: 35px;'>
<div class="col-md-12" style='background-color: #3e3e3e; height: 240px;'>
<div class = "col-md-3">
<h1 style="font-size: 60px; color: white;">Qiita</h1>  <br> <br>
<p class="white"> How developers code is here. </p> <br> <br>
<p class="ori">©︎2011-2020 Increments Inc.</p>
</div>

<div class="col-md-3">
<p class="white ue" style="margin-top: 50px;"><strong>Qiita</strong></p>
<a href="https://qiita.com/about" class="ori ma y">about</a>     <a href="https://qiita.com/api/v2/docs" class="ori ma">API</a> <br> <br>
<a href="https://qiita.com/terms" class="ori ma y">利用規約</a><a href="https://qiita.com/feedback/new" class="ori ma">ご意見</a> <br> <br>
<a href="https://qiita.com/privacy" class="ori ma y">プライバシー</a></a><a href="https://help.qiita.com/" class="ori ma">ヘルプ</a> <br> <br>
<a href="https://help.qiita.com/ja/articles/qiita-community-guideline" class="ori ma y">ガイドライン</a></a><a href="https://qiita.com/ads?utm_source=qiita&utm_medium=referral&utm_content=footer" class="ori ma">広告掲載</a>
</div>
<div class="col-md-offset-1"></div>
<div class="col-md-3">
<p class="white ue" style="margin-top: 50px;"><strong>Increments</strong></p>
<a href="https://increments.co.jp/company/" class="ori ma y">about</a>     <a href="https://teams.qiita.com/" class="ori ma">Qiita Team</a> <br> <br>
<a href="https://increments.co.jp/jobs/" class="ori ma y">採用情報</a><a href="https://jobs.qiita.com/?utm_source=qiita&utm_medium=referral&utm_content=footer" class="ori ma">Qiita Jobs</a> <br> <br>
<a href="https://blog.qiita.com/" class="ori ma y">ブログ</a></a><a href="https://zine.qiita.com/?utm_source=qiita&utm_medium=referral&utm_content=footer" class="ori ma">Qiita Zine</a> <br> <br>
</div>
</div>
</div>

app/views/layouts/_footer.html.slim
.row[style="margin-top: 35px;"]
  .col-md-12[style="background-color: #3e3e3e; height: 240px;"]
    .col-md-3
      h1[style="font-size: 60px; color: white;"]
        | Qiita
      br
      br
      p.white
        |  How developers code is here. 
      br
      br
      p.ori
        | ©︎2011-2020 Increments Inc.
    .col-md-3
      p.white.ue[style="margin-top: 50px;"]
        strong
          | Qiita
      a.ori.ma.y[href="https://qiita.com/about"]
        | about
      a.ori.ma[href="https://qiita.com/api/v2/docs"]
        | API
      br
      br
      a.ori.ma.y[href="https://qiita.com/terms"]
        | 利用規約
      a.ori.ma[href="https://qiita.com/feedback/new"]
        | ご意見
      br
      br
      a.ori.ma.y[href="https://qiita.com/privacy"]
        | プライバシー
      a.ori.ma[href="https://help.qiita.com/"]
        | ヘルプ
      br
      br
      a.ori.ma.y[href="https://help.qiita.com/ja/articles/qiita-community-guideline"]
        | ガイドライン
      a.ori.ma[href="https://qiita.com/ads?utm_source=qiita&utm_medium=referral&utm_content=footer"]
        | 広告掲載
    .col-md-offset-1
    .col-md-3
      p.white.ue[style="margin-top: 50px;"]
        strong
          | Increments
      a.ori.ma.y[href="https://increments.co.jp/company/"]
        | about
      a.ori.ma[href="https://teams.qiita.com/"]
        | Qiita Team
      br
      br
      a.ori.ma.y[href="https://increments.co.jp/jobs/"]
        | 採用情報
      a.ori.ma[href="https://jobs.qiita.com/?utm_source=qiita&utm_medium=referral&utm_content=footer"]
        | Qiita Jobs
      br
      br
      a.ori.ma.y[href="https://blog.qiita.com/"]
        | ブログ
      a.ori.ma[href="https://zine.qiita.com/?utm_source=qiita&utm_medium=referral&utm_content=footer"]
        | Qiita Zine
      br
      br

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
<nav class="navbar navbar-light" style='background-color: pink;'>
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#Navber" aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          </div><!-- /.navbar-header -->
    <div class="collapse navbar-collapse" id="Navber">
      <ul class="nav navbar-nav">
            <%= link_to 'Qiita', contents_path, class: 'navbar-brand' %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">ホーム<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'トレンド', contents_path, class: 'glyphicon glyphicon-check' %></li>
            <li><%= link_to 'タイムライン', timeline_content_path(current_user), class: 'glyphicon glyphicon-list' %></li>
            <li><%= link_to 'タグフィールド', tag_field_content_path(current_user), class: 'glyphicon glyphicon-tags' %></li>
            <li><%= link_to 'マイルストーン', mile_stone_content_path(current_user), class: 'glyphicon glyphicon-unchecked' %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">コミュニティ<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'ユーザー一覧', users_path %></li>
          </ul>
        </li>
      </ul>
        <div class="navbar-right">
        <%= link_to 'お知らせ', notifications_path, class: 'navbar-brand' %>
        <%= link_to 'ストック一覧', confirm_content_path(current_user), class: 'navbar-brand' %>
        <%= link_to '投稿する', new_content_path, class: 'navbar-brand glyphicon glyphicon-new-window' %>
        <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'マイページ', user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to '下書き一覧(draft)', confirm_content_path(current_user) %></li>
            <li><%= link_to '編集リクエスト', edit_request_contents_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to '設定', edit_user_path(current_user) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to ' ログアウト', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout' %></li>
          </ul>
        </li>
        </ul>
        </div>
    </div><!-- /.navbar-collapse -->
    <% else %>
    <% end %>
    </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header.html.slim
- if user_signed_in?
  nav.navbar.navbar-light[style="background-color: pink;"]
    .container-fluid
      .navbar-header
        button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#Navber" aria-expanded="false"]
          span.sr-only
          span.icon-bar
          span.icon-bar
          span.icon-bar
      #Navber.collapse.navbar-collapse
        ul.nav.navbar-nav
          = link_to 'Qiita', contents_path, class: 'navbar-brand'
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              | ホーム
              span.caret
            ul.dropdown-menu
              li
                = link_to 'トレンド', contents_path, class: 'glyphicon glyphicon-check'
              li
                = link_to 'タイムライン', timeline_content_path(current_user), class: 'glyphicon glyphicon-list'
              li
                = link_to 'マイルストーン', mile_stone_content_path(current_user), class: 'glyphicon glyphicon-unchecked'
          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              | コミュニティ
              span.caret
            ul.dropdown-menu
              li
                = link_to 'ユーザー一覧', users_path
        .navbar-right
          = link_to 'お知らせ', notifications_path, class: 'navbar-brand'
          = link_to 'ストック一覧', confirm_content_path(current_user), class: 'navbar-brand'
          = link_to '投稿する', new_content_path, class: 'navbar-brand glyphicon glyphicon-new-window'
          ul.nav.navbar-nav
            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown"]
                span.caret
              ul.dropdown-menu
                li
                  = link_to 'マイページ', user_path(current_user)
                li.divider[role="separator"]
                li
                  = link_to '下書き一覧(draft)', confirm_content_path(current_user)
                li
                  = link_to '編集リクエスト', edit_request_contents_path
                li.divider[role="separator"]
                li
                  a[href="#"]
                    | 設定
                li
                  a[href="#"]
                    | ヘルプ
                li.divider[role="separator"]
                li
                  = link_to ' ログアウト', destroy_user_session_path, method: :delete,class: 'glyphicon glyphicon-log-out logout'
- else

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qiita</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div> 
    <div style='marign-top: 50px;'><%= render 'layouts/footer' %></div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qiita
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    .container
      = yield
    div[style="marign-top: 50px;"]
      = render 'layouts/footer'